<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Void.Chef.Domain.UnitTests</RootNamespace>
        <AssemblyName>Void.Chef.Domain.UnitTests</AssemblyName>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Domain\Domain.csproj" />
    </ItemGroup>

</Project>
